backend/urls.py
from django.conf.urls import url

from . import views

app_name = 'backend'
urlpatterns = [
    url(r'^query/$', views.query, name='query'),
    url(r'^tips/$', views.tips, name='tips'),
]

frontend/urls.py
from django.conf.urls import url

from . import views

app_name = 'frontend'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

qa/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', include('backend.urls')),
    url(r'^', include('frontend.urls')),
]

frontend/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render

# Create your views here.


def index(request):
    return render(request, 'frontend/index.html')

frontend/templates/frontend/index.html
{% load i18n static %}<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <meta content="text/html; charset=utf-8" http-equiv="content-type" />
        <meta content="qa" name="description" />
        <title>QA</title>
        <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" rel="stylesheet">
        <link href="//cdn.bootcss.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'frontend/css/jquery.jsonview.css' %}">
        <!--link rel="stylesheet" type="text/css" href="{% static 'frontend/css/style.css' %}"-->
        <script src="//cdn.bootcss.com/jquery/3.1.1/jquery.min.js"></script>
        <script src="//cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
        <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="{% static 'frontend/js/jquery.jsonview.js' %}"></script>
        <!--script src="{% static 'frontend/js/index.js' %}"></script-->
        <script>
            var api_query = "{% url 'backend:query' %}";
            var api_tips = "{% url 'backend:tips' %}";
        </script>
        <script>
$(document).ready(init);

var backend_status = null;

function getRandomColor() {
    var letters = '0123456789ABCDEF';
    var color = '#';
    for (var i = 0; i < 6; i++ ) {
        color += letters[Math.floor(Math.random() * 16)];
    }
    return color;
}

function init() {
    $('#input-query').bind('keydown', function(e) {
        var event = e || window.event;
        var code = event.keyCode || event.which || event.charCode;
        if (code == '\n'.charCodeAt(0) || code == '\r'.charCodeAt(0)) {
            e.preventDefault();
            $("#button-query").click();
        }
    }).focus();
    $('#button-query').click(function() {
        var text = $('#input-query')[0].value;
        if (!text) return;
        $.ajax({
            url: api_query,
            method: 'POST',
            data: {
                csrfmiddlewaretoken: $.cookie('csrftoken'),
                status: backend_status,
                text: text,
            },
            success: function(data) {
                if (data.error) {
                    alert(data.msg);
                    return;
                }
                console.log(data.msg);
                backend_status = data.msg.status;
                var wrapper = $('<div></div>');
                wrapper.addClass('view-query');
                $.map(data.msg.products, function(p) {
                    var div = $('.templates .computer-summary').clone();
                    div.find('#image').attr('src', p['img'].replace('_80x60', '_280x210'));
                    div.find('#title').text(p['型号']);
                    div.find('#title').attr('href', p['link']);
                    div.find('#price').text(p['price']);
                    div.find('#cpu').text(p['CPU型号'] + ' @' + p['CPU主频']);
                    div.find('#memory').text(p['内存容量']);
                    div.find('#disk').text(p['硬盘容量'] + ' ' + p['硬盘描述']);
                    div.find('#screen').text(p['屏幕尺寸']);
                    div.find('#cpu_freq').text(p['CPU主频']);
                    div.find('#gpu').text(p['显卡芯片']);
                    div.find('#gpu_size').text(p['显存容量']);
                    div.find('#market_time').text(p['上市时间']);
                    div.find('#color').text(p['外壳材质'] + ' ' + p['外壳描述']);
                    div.find('#weight').text(p['笔记本重量']);
                    wrapper.append(div);
                });
                var div = $('.templates .message-show').clone();
                div.find('#content').text(data.msg.message);
                wrapper.append(div);
                var div = $('.templates .debug-show').clone();
                var debug_json = JSON.parse(backend_status);
                delete debug_json.last_products;
                delete debug_json.last_status;
                // div.JSONView(debug_json, { collapsed: false });
                wrapper.append(div);
                $('.view').empty().append(wrapper);
            },
            error: function(e) {
                var wrapper = $('<div></div>');
                wrapper.text('ajax failed');
                $('.view').empty().append(wrapper);
            }
        });
    });
    $('#button-tips').click(function() {
        $.ajax({
            url: api_tips,
            method: 'POST',
            data: {
                csrfmiddlewaretoken: $.cookie('csrftoken'),
                status: backend_status,
            },
            success: function(data) {
                if (data.error) {
                    alert(data.msg);
                    return;
                }
                backend_status = data.status;
                var div = $('<div></div>');
                var p = $('<p></p>');
                p.text(JSON.stringify(data.msg));
                div.addClass('view-tips');
                div.append(p);
                $('.view').empty().append(div);
            },
            error: function(e) {
                var wrapper = $('<div></div>');
                wrapper.text('ajax failed');
                $('.view').empty().append(wrapper);
            }
        });
    });
}
        </script>
        <style>
        .view {
            margin-top: 2em;
        }
        #query-line {
            position: fixed;
            height: 80px;
            bottom: 0;
            left: 20%;
            right: 20%;
        }
        #input-query {
            width: 80%;
        }
        .template {
        }
        .computer-summary {
        }
        .message-show {
            margin-top: 2em;
        }
        </style>
    </head>
    <body>
        {% csrf_token %}
        <div class="container" align="center">
            <div class="view">
                <div>
                    <h3>请问您有什么需求？</h3>
                </div>
            </div>
            <div id="query-line" class="form-inline">
                <input id="input-query" class="form-control" placeholder="您还有什么要求吗？"/>
                <button id="button-query" class="btn btn-default">Submit</button>
                <!-- <button id="button-tips" class="btn btn-default">Tips</button> -->
            </div>
        </div>
        <div class="templates" hidden>
            <div>
                
            </div>
            <div class="computer-summary">
                <div class="row">
                    <div class="col-sm-4">
                        <img id="image" class="img-rounded" style="width: 80%"/>
                    </div>
                    <div class="col-sm-6">
                        <div class="row"><h3><a id="title" target="_blank">名称</a></h3></div>
                        <div class="row" style="color: red"><h3><span id="price">价格</span> 元</h3></div>
                    </div>
                    <div class="col-sm-2">
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-3">
                        <h4>配置参数</h4>
                    </div>
                    <div class="col-sm-9">
                    </div>
                    <div class="col-sm-12">
                        <div class="row">
                            <div class="col-sm-3"><b>CPU</b></div>
                            <div class="col-sm-3" id="cpu"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><b>内存</b></div>
                            <div class="col-sm-3" id="memory"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><b>硬盘</b></div>
                            <div class="col-sm-3" id="disk"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><b>屏幕</b></div>
                            <div class="col-sm-3" id="screen"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><b>GPU</b></div>
                            <div class="col-sm-3"><span id="gpu"></span> (<span id="gpu_size"></span>)</div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><b>上市时间</b></div>
                            <div class="col-sm-3" id="market_time"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><b>外壳颜色</b></div>
                            <div class="col-sm-3" id="color"></div>
                        </div>
                        <div class="row">
                            <div class="col-sm-3"><b>重量</b></div>
                            <div class="col-sm-3" id="weight"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="message-show">
                <h2 id="content"></h2>
            </div>
            <div class="debug-show" align="left">
            </div>
        </div>
    </body>
</html>